### ISSUE TITLE
Skal vi oppgrade til Jekyll 3.0?

### ISSUE THREAD

**Issue by torbjornvatn** [unacast/unacast.github.io#11]
Ref. https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by heim** [comment]
Next blogger does it.

**Comment by torbjornvatn** [comment]
Vi kan godt prøve å fikse SOME-knappene i samme slengen også. Blir så dårlige thumbnails.

**Comment by heim** [comment]
Closing
